// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.0--rc2
// source: pots.proto

package pots

import (
	common "github.com/urealaden/cova-cents/server/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        float64                `protobuf:"fixed64,3,opt,name=target,proto3" json:"target,omitempty"`
	Theme         string                 `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pot) Reset() {
	*x = Pot{}
	mi := &file_pots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pot) ProtoMessage() {}

func (x *Pot) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pot.ProtoReflect.Descriptor instead.
func (*Pot) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{0}
}

func (x *Pot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pot) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Pot) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type AddPotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target        float64                `protobuf:"fixed64,2,opt,name=target,proto3" json:"target,omitempty"`
	Theme         string                 `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPotRequest) Reset() {
	*x = AddPotRequest{}
	mi := &file_pots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPotRequest) ProtoMessage() {}

func (x *AddPotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPotRequest.ProtoReflect.Descriptor instead.
func (*AddPotRequest) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{1}
}

func (x *AddPotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPotRequest) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *AddPotRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type AddPotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        float64                `protobuf:"fixed64,3,opt,name=target,proto3" json:"target,omitempty"`
	Theme         string                 `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`
	Status        *common.Status         `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPotResponse) Reset() {
	*x = AddPotResponse{}
	mi := &file_pots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPotResponse) ProtoMessage() {}

func (x *AddPotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPotResponse.ProtoReflect.Descriptor instead.
func (*AddPotResponse) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{2}
}

func (x *AddPotResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddPotResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPotResponse) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *AddPotResponse) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *AddPotResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type RetrievePotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievePotsRequest) Reset() {
	*x = RetrievePotsRequest{}
	mi := &file_pots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievePotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievePotsRequest) ProtoMessage() {}

func (x *RetrievePotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievePotsRequest.ProtoReflect.Descriptor instead.
func (*RetrievePotsRequest) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{3}
}

func (x *RetrievePotsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetrievePotsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RetrievePotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pots          []*Pot                 `protobuf:"bytes,1,rep,name=pots,proto3" json:"pots,omitempty"`
	Status        *common.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievePotsResponse) Reset() {
	*x = RetrievePotsResponse{}
	mi := &file_pots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievePotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievePotsResponse) ProtoMessage() {}

func (x *RetrievePotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievePotsResponse.ProtoReflect.Descriptor instead.
func (*RetrievePotsResponse) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{4}
}

func (x *RetrievePotsResponse) GetPots() []*Pot {
	if x != nil {
		return x.Pots
	}
	return nil
}

func (x *RetrievePotsResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdatePotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        float64                `protobuf:"fixed64,3,opt,name=target,proto3" json:"target,omitempty"`
	Theme         string                 `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePotRequest) Reset() {
	*x = UpdatePotRequest{}
	mi := &file_pots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePotRequest) ProtoMessage() {}

func (x *UpdatePotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePotRequest.ProtoReflect.Descriptor instead.
func (*UpdatePotRequest) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePotRequest) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *UpdatePotRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type UpdatePotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Target        float64                `protobuf:"fixed64,3,opt,name=target,proto3" json:"target,omitempty"`
	Theme         string                 `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`
	Status        *common.Status         `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePotResponse) Reset() {
	*x = UpdatePotResponse{}
	mi := &file_pots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePotResponse) ProtoMessage() {}

func (x *UpdatePotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePotResponse.ProtoReflect.Descriptor instead.
func (*UpdatePotResponse) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePotResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePotResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePotResponse) GetTarget() float64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *UpdatePotResponse) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UpdatePotResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeletePotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePotRequest) Reset() {
	*x = DeletePotRequest{}
	mi := &file_pots_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePotRequest) ProtoMessage() {}

func (x *DeletePotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePotRequest.ProtoReflect.Descriptor instead.
func (*DeletePotRequest) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePotResponse) Reset() {
	*x = DeletePotResponse{}
	mi := &file_pots_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePotResponse) ProtoMessage() {}

func (x *DeletePotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pots_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePotResponse.ProtoReflect.Descriptor instead.
func (*DeletePotResponse) Descriptor() ([]byte, []int) {
	return file_pots_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePotResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_pots_proto protoreflect.FileDescriptor

var file_pots_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6f, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x03, 0x50, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x0d,
	0x41, 0x64, 0x64, 0x50, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x22,
	0x8b, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x43, 0x0a,
	0x13, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x50, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0x61, 0x0a, 0x14, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x50, 0x6f,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x70, 0x6f,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x50, 0x6f, 0x74, 0x52, 0x04, 0x70, 0x6f, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x64, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68,
	0x65, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x22, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x72, 0x65,
	0x61, 0x6c, 0x61, 0x64, 0x65, 0x6e, 0x2f, 0x63, 0x6f, 0x76, 0x61, 0x2d, 0x63, 0x65, 0x6e, 0x74,
	0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x6f, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pots_proto_rawDescOnce sync.Once
	file_pots_proto_rawDescData = file_pots_proto_rawDesc
)

func file_pots_proto_rawDescGZIP() []byte {
	file_pots_proto_rawDescOnce.Do(func() {
		file_pots_proto_rawDescData = protoimpl.X.CompressGZIP(file_pots_proto_rawDescData)
	})
	return file_pots_proto_rawDescData
}

var file_pots_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pots_proto_goTypes = []any{
	(*Pot)(nil),                  // 0: finance.Pot
	(*AddPotRequest)(nil),        // 1: finance.AddPotRequest
	(*AddPotResponse)(nil),       // 2: finance.AddPotResponse
	(*RetrievePotsRequest)(nil),  // 3: finance.RetrievePotsRequest
	(*RetrievePotsResponse)(nil), // 4: finance.RetrievePotsResponse
	(*UpdatePotRequest)(nil),     // 5: finance.UpdatePotRequest
	(*UpdatePotResponse)(nil),    // 6: finance.UpdatePotResponse
	(*DeletePotRequest)(nil),     // 7: finance.DeletePotRequest
	(*DeletePotResponse)(nil),    // 8: finance.DeletePotResponse
	(*common.Status)(nil),        // 9: finance.Status
}
var file_pots_proto_depIdxs = []int32{
	9, // 0: finance.AddPotResponse.status:type_name -> finance.Status
	0, // 1: finance.RetrievePotsResponse.pots:type_name -> finance.Pot
	9, // 2: finance.RetrievePotsResponse.status:type_name -> finance.Status
	9, // 3: finance.UpdatePotResponse.status:type_name -> finance.Status
	9, // 4: finance.DeletePotResponse.status:type_name -> finance.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pots_proto_init() }
func file_pots_proto_init() {
	if File_pots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pots_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pots_proto_goTypes,
		DependencyIndexes: file_pots_proto_depIdxs,
		MessageInfos:      file_pots_proto_msgTypes,
	}.Build()
	File_pots_proto = out.File
	file_pots_proto_rawDesc = nil
	file_pots_proto_goTypes = nil
	file_pots_proto_depIdxs = nil
}
